DEBUG T3 [main] org.apache.log4j.net.SocketServerTestCase (X) Message 1
DEBUG T3 [main] org.apache.log4j.net.SocketServerTestCase (X) Message 2
 INFO T3 [main] org.apache.log4j.net.SocketServerTestCase (X) Message 3
 WARN T3 [main] org.apache.log4j.net.SocketServerTestCase (X) Message 4
LETHAL T3 [main] org.apache.log4j.net.SocketServerTestCase (X) Message 5
DEBUG T3 [main] org.apache.log4j.net.SocketServerTestCase (X) Message 6
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(X)
	at org.apache.log4j.net.SocketServerTestCase.test3(X)
	at java.lang.reflect.Method.invoke(X)
	at junit.framework.TestCase.runTest(X)
	at junit.framework.TestCase.runBare(X)
	at junit.framework.TestResult$1.protect(X)
	at junit.framework.TestResult.runProtected(X)
	at junit.framework.TestResult.run(X)
	at junit.framework.TestCase.run(X)
	at junit.framework.TestSuite.runTest(X)
	at junit.framework.TestSuite.run(X)
ERROR T3 [main] org.apache.log4j.net.SocketServerTestCase (X) Message 7
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(X)
	at org.apache.log4j.net.SocketServerTestCase.test3(X)
	at java.lang.reflect.Method.invoke(X)
	at junit.framework.TestCase.runTest(X)
	at junit.framework.TestCase.runBare(X)
	at junit.framework.TestResult$1.protect(X)
	at junit.framework.TestResult.runProtected(X)
	at junit.framework.TestResult.run(X)
	at junit.framework.TestCase.run(X)
	at junit.framework.TestSuite.runTest(X)
	at junit.framework.TestSuite.run(X)
