DEBUG T1 [main] org.apache.log4j.net.SocketServerTestCase Message 1
DEBUG T1 [main] root Message 2
 INFO T1 [main] org.apache.log4j.net.SocketServerTestCase Message 3
 WARN T1 [main] org.apache.log4j.net.SocketServerTestCase Message 4
LETHAL T1 [main] org.apache.log4j.net.SocketServerTestCase Message 5
DEBUG T1 [main] org.apache.log4j.net.SocketServerTestCase Message 6
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(X)
	at org.apache.log4j.net.SocketServerTestCase.test1(X)
	at java.lang.reflect.Method.invoke(X)
	at junit.framework.TestCase.runTest(X)
	at junit.framework.TestCase.runBare(X)
	at junit.framework.TestResult$1.protect(X)
	at junit.framework.TestResult.runProtected(X)
	at junit.framework.TestResult.run(X)
	at junit.framework.TestCase.run(X)
	at junit.framework.TestSuite.runTest(X)
	at junit.framework.TestSuite.run(X)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(X)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(X)
ERROR T1 [main] root Message 7
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(X)
	at org.apache.log4j.net.SocketServerTestCase.test1(X)
	at java.lang.reflect.Method.invoke(X)
	at junit.framework.TestCase.runTest(X)
	at junit.framework.TestCase.runBare(X)
	at junit.framework.TestResult$1.protect(X)
	at junit.framework.TestResult.runProtected(X)
	at junit.framework.TestResult.run(X)
	at junit.framework.TestCase.run(X)
	at junit.framework.TestSuite.runTest(X)
	at junit.framework.TestSuite.run(X)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(X)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(X)
