DEBUG some5 T5 MDC-TEST5 [main] SocketServerTestCase - Message 1
DEBUG some5 T5 MDC-TEST5 [main] root - Message 2
 INFO some5 T5 MDC-TEST5 [main] SocketServerTestCase - Message 3
 WARN some5 T5 MDC-TEST5 [main] SocketServerTestCase - Message 4
LETHAL some5 T5 MDC-TEST5 [main] SocketServerTestCase - Message 5
DEBUG some5 T5 MDC-TEST5 [main] SocketServerTestCase - Message 6
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(X)
	at org.apache.log4j.net.SocketServerTestCase.test5(X)
	at java.lang.reflect.Method.invoke(X)
	at junit.framework.TestCase.runTest(X)
	at junit.framework.TestCase.runBare(X)
	at junit.framework.TestResult$1.protect(X)
	at junit.framework.TestResult.runProtected(X)
	at junit.framework.TestResult.run(X)
	at junit.framework.TestCase.run(X)
	at junit.framework.TestSuite.runTest(X)
	at junit.framework.TestSuite.run(X)
ERROR some5 T5 MDC-TEST5 [main] root - Message 7
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(X)
	at org.apache.log4j.net.SocketServerTestCase.test5(X)
	at java.lang.reflect.Method.invoke(X)
	at junit.framework.TestCase.runTest(X)
	at junit.framework.TestCase.runBare(X)
	at junit.framework.TestResult$1.protect(X)
	at junit.framework.TestResult.runProtected(X)
	at junit.framework.TestResult.run(X)
	at junit.framework.TestCase.run(X)
	at junit.framework.TestSuite.runTest(X)
	at junit.framework.TestSuite.run(X)
